config/routes.rb
Rails.application.routes.draw do
  delete '/albums/:album_id/delete_selected', to: "photos#delete_selected", as: 'delete_selected'
  delete '/albums/:album_id/delete_all', to: "photos#delete_all", as: 'delete_all'

  resources :posts
  resources :photos, only: [:index]
  resources :albums do
    resources :photos, only: [:create]
  end
  post '/tinymce_assets' => 'posts#upload_image'
  devise_for :admins
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :albums
  has_many :photos
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :admin
  has_many :photos, dependent: :destroy
  validates :name, presence: true
  default_scope { order(id: :desc) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_uploader.rb
class ImageUploader < Shrine
  # plugins and uploading logic
  plugin :store_dimensions
  plugin :processing

  process(:store) do |io, context|
    original = io.download { |cmd| cmd.auto_orient }
    original
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  include ImageUploader[:image]
  belongs_to :admin
  belongs_to :album
  validates :image, presence: true
  default_scope { order(id: :desc) }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :admin
  validates :title, presence: true
  validates :content, presence: true
  default_scope { order(id: :desc) }

  def previous
    Post.where(["id < ?", id]).first
  end

  def next
    Post.where(["id > ?", id]).last
  end
end

app/models/tinymce_asset.rb
class TinymceAsset < ApplicationRecord
  include ImageUploader[:image]
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = Album.all
    @album = Album.new
  end

  def create
    @album = current_admin.albums.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
      else
        format.js
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
      else
        format.js
      end
    end
  end

  def show
    @photo = Photo.new
  end

  def destroy
    @album.destroy
    redirect_to albums_path, notice: 'Album was successfully destroyed.'
  end

  private
  def set_album
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_admin!, except: [:index]
  before_action :set_album, except: [:index]

  def index
    @photos = Photo.all
  end

  def create
    respond_to do |format|
      if params[:photo]
        photo_params[:image].each do |image_file|
          @photo = current_admin.photos.create(image: image_file, album: @album)
        end
        format.html {redirect_to @album}
      elsif params[:file]
        @photo = current_admin.photos.create(image: params[:file], album: @album)
        photo_data = { url: @photo.image_url, size: "#{@photo.image.width}x#{@photo.image.height}" }
        format.json {render json: photo_data, status: 200}
      else
        format.html {redirect_to @album}
      end
    end
  end

  def delete_selected
    Photo.where(id: params[:photos]).delete_all
    redirect_to @album
  end

  def delete_all
    @album.photos.delete_all
    redirect_to @album
  end

  private
  def set_album
    @album = Album.find(params[:album_id])
  end

  def photo_params
    params.require(:photo).permit(:image, :image_data, image: [])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
    @years = @posts.map {|post| post.created_at.year}.uniq
    @posts_archive = @posts.group_by {|post| [post.created_at.year, post.created_at.month]}
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_admin.posts.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def upload_image
    image = TinymceAsset.create(image: params[:file])
    render json: { image: { url: image.image_url } }, content_type: 'text/html'
  end

  private
  def set_post
      @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/albums/_form.html.erb
<%= simple_form_for album, remote: true do |f| %>
  <div class="row align-center">
    <div class="small-12 medium-9 column">
      <%= f.input :name %>
    </div>
    <div class="small-8 medium-3 column text-right">
      <%= f.submit action, class: "button expanded" %>
    </div>
  </div>
<% end %>

app/views/albums/create.js.erb
$(".error").remove();

<% @album.errors.full_messages.each do |msg| %>
  $(".album_name").append("<span class='error'><i class='fa fa-exclamation-circle'></i> <%= msg %></span>").hide().fadeIn(100);
<% end %>

$('#album_name').focus(function() {
  $('.error').remove();
})

app/views/albums/edit.html.erb
<%= form_tag delete_selected_path(@album), method: :delete, id: "edit-album-form" do %>

  <div class="row align-center">
    <div class="column small-12 medium-10 large-8">
      <%= render "shared/breadcrumbs" %>

      <div class="row">
        <div class="column">
          <h4>
            <%= @album.name %>
          </h4>
        </div>

        <div class="shrink column">
          <a data-open="album-form" class="button success">
            Edit
          </a>
          <%= content_tag :button, type: :submit, class: "button alert" do %>
            <i class="fa fa-times" aria-hidden="true"></i> Selected
          <% end %>

          <%= link_to delete_all_path(@album), method: :delete, "data-confirm": "Are you sure you want to delete all photos in this album?", class: "button alert" do %>
            <i class="fa fa-times" aria-hidden="true"></i> All
          <% end %>
        </div>
      </div>

      <%= render "shared/gallery", gallery: @album.photos, edit: true %>

    </div>

  </div>
<% end %>

<div class="reveal" id="album-form" data-reveal>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
  <h6 class="text-center">New Album</h6>
  <%= render "form", album: @album, action: "Update" %>
</div>

app/views/albums/index.html.erb
<div class="row align-center albums-all">
  <div class="column small-12 medium-10 large-8">
    <%= render "shared/tabs" %>

    <div class="row">
      <% @albums.each do |album| %>
        <div class="column small-6 medium-4 large-3 photo-container">
          <%= link_to album_path(album) do %>
            <div class="photo-link">
              <% if album.photos.blank? %>
                <img style="background-image:url(http://placehold.it/300x300?text=No+Photos);" class="photo-image album-image"/>
              <% else %>
                <img style="background-image:url(<%= album.photos.first.image_url %>);" class="photo-image album-image" />
              <% end %>
            </div>
            <p class="album-name">
              <%= album.name %>
            </p>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>
</div>

<% if admin_signed_in? %>
  <div class="reveal" id="album-form" data-reveal>
    <button class="close-button" data-close aria-label="Close modal" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
    <h6 class="text-center">New Album</h6>
    <%= render "form", album: @album, action: "Create" %>
  </div>
<% end %>

app/views/albums/show.html.erb
<div class="albums-show row align-center">
  <div class="column small-12 medium-10 large-8">
    <%= render "shared/breadcrumbs" %>
    <div class="row">
      <div class="column">
        <h4>
          <%= @album.name %>
        </h4>
      </div>
      <% if admin_signed_in? %>
        <div class="shrink column">
          <ul class="menu remove-first-child-padding">
            <li>
              <a data-open="dropzone-form" class="upload-link">
                <i class="fa fa-upload" aria-hidden="true"></i>
              </a>
            </li>
            <li>
              <%= link_to edit_album_path(@album), class: "edit-link" do %>
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              <% end %>
            </li>
            <li>
              <%= link_to @album, method: :delete, "data-confirm": "Are you sure you want to delete this album?", class: "delete-link" do %>
                  <i class="fa fa-trash" aria-hidden="true"></i>
                <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>

    <% if @album.photos.blank? %>
      <div class="row column text-center" id="empty-album">
        <h4 class="subheader">
          This album is empty.
        </h4>
      </div>
    <% end %>

    <%= render "shared/gallery", gallery: @album.photos, edit: false %>
  </div>
</div>

<div class="reveal" id="dropzone-form" data-reveal>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
  <h6><strong>Upload Here</strong></h6>
  <%= form_for [@album, @photo], html: {class: "dropzone"} do |f| %>
    <div class="fallback">
      <%= f.file_field :image, multiple: true %>
      <%= f.submit "Upload" %>
    </div>
  <% end %>
</div>

<%= render "shared/photoswipe" %>

app/views/albums/update.js.erb
$(".error").remove();

<% @album.errors.full_messages.each do |msg| %>
  $(".album_name").append("<span class='error'><i class='fa fa-exclamation-circle'></i> <%= msg %></span>").hide().fadeIn(100);
<% end %>

$('#album_name').focus(function() {
  $('.error').remove();
})

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Our Blog" %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body class="<%= content_for(:body_class) || request.controller_class.name.downcase.gsub('controller','') %>">
    <div class="off-canvas-wrapper">
      <div class="off-canvas-content" data-off-canvas-content>
        <%= render "navigation/topbar" %>

        <% flash.each do |name, msg| %>
          <div class="row column">
            <div class="callout <%= name %>">
              <%= msg %>
            </div>
          </div>
        <% end %>

        <div class="row column">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/navigation/_topbar.html.erb
<div class="top-bar">
  <div class="top-bar-title">
    <a data-toggle="sidebar-menu" class="hide-for-large top-bar-hamburger">
      <i class="fa fa-bars" aria-hidden="true"></i>
    </a>
    <%= link_to "Our Blog", root_path %>
  </div>
  <div class="top-bar-right show-for-large">
    <ul class="menu">
      <li>
        <%= link_to "Photos", photos_path %>
      </li>
      <li>
        <a>To Do</a>
      </li>
      <li>
        <a>About</a>
      </li>
      <li>
        <%= link_to "New Post", new_post_path %>
      </li>
      <li>
        <ul class="dropdown menu" data-dropdown-menu data-disable-hover="true" data-click-open="true">
        <li>
          <a class="topbar-dropdown-link"><i class="fa fa-cog" aria-hidden="true"></i></a>
          <ul class="menu vertical">
            <li><a href="#">Profile</a></li>
            <hr class="menu-divider"/>
            <li>
              <% if admin_signed_in? %>
                <%= link_to "Log Out", destroy_admin_session_path, method: :delete %>
              <% else %>
                <%= link_to "Log In", new_admin_session_path %>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
      </li>
    </ul>
  </div>
</div>

<div class="off-canvas position-left" id="sidebar-menu" data-off-canvas>
  <!-- Your menu or Off-canvas content goes here -->
  <ul class="vertical menu">
    <li class="text-right">
      <a aria-label="Close menu" data-close>
        <i class="fa fa-times" aria-hidden="true"></i>
      </a>
    </li>
    <li class="text-center">
      <%= link_to "Photos", photos_path %>
    </li>
    <li class="text-center"><a href="#">Two</a></li>
    <li class="text-center"><a href="#">Three</a></li>
    <li class="text-center">
      <%= link_to "New Post", new_post_path %>
    </li>
    <hr/>
    <li class="text-center">
      <a href="#">Profile</a>
    </li>
    <li class="text-center">
      <% if admin_signed_in? %>
        <%= link_to "Log Out", destroy_admin_session_path, method: :delete %>
      <% else %>
        <%= link_to "Log In", new_admin_session_path %>
      <% end %>
    </li>
  </ul>
</div>

app/views/photos/index.html.erb
<div class="row align-center">
  <div class="column small-12 medium-10 large-8">
    <%= render "shared/tabs" %>
    <%= render "shared/gallery", gallery: @photos, edit: false %>
    <%= render "shared/photoswipe" %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :content, input_html: {class: "tinymce", rows: 15} %>
  <div class="row align-center">
    <%= f.submit class: "button success column small-6 medium-4" %>
  </div>
<% end %>
<%= tinymce menubar: false %>

app/views/posts/edit.html.erb
<div class="posts-form">
  <div class="row align-middle">
    <div class="column">
      <h4>Edit Post</h4>
    </div>
    <div class="shrink column">
      <%= link_to "Back", @post, class: "float-right button secondary back-button" %>
    </div>
  </div>
  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<div class="row posts-container">
  <div class="column small-12 large-9 small-order-2 large-order-1">
    <% @posts.each do |post| %>
      <div class="post">
        <%= link_to post_path(post) do %>
          <div class="post-title">
            <h4><%= post.title %></h4>
            <p><%= post.created_at.strftime("%d %B %Y")%></p>
          </div>
        <% end %>
        <div class="post-content">
          <%= post.content.html_safe %>
        </div>
        </div>
    <% end %>
  </div>

  <div class="column small-12 large-3 small-order-1 large-order-2">
    <h6 class="archive">
      Archives
    </h6>
    <ul class="vertical menu posts-archive" data-accordion-menu>
      <% @years.each do |year| %>
        <li>
          <%= link_to year, "#" %>
          <ul class="menu vertical nested">
            <% @posts_archive.each do |yr_month, post_arr| %>
              <% if yr_month.first == year %>
                <li>
                  <%= link_to I18n.t("date.abbr_month_names")[yr_month.last], "#" %>
                  <ul class="menu vertical nested">
                    <% post_arr.each do |post| %>
                      <li><%= link_to "#{post.created_at.day} - #{post.title}", post_path(post) %></li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/posts/new.html.erb
<div class="posts-form">
  <h4>New Post</h4>
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="posts-show row align-center">
  <div class="column small-12 medium-10 large-8">
    <div class="row">
      <div class="column">
        <h4>
          <%= @post.title %>
        </h4>
      </div>
      <% if admin_signed_in? %>
        <div class="shrink column">
          <ul class="menu remove-first-child-padding">
            <li>
              <%= link_to edit_post_path(@post), class: "edit-link" do %>
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              <% end %>
            </li>
            <li>
              <%= link_to @post, method: :delete, class: "delete-link", data: { confirm: 'Are you sure?'}  do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>

    <div class="row align-middle">
      <div class="column">
        <h6 class="subheader">
          <%= @post.created_at.strftime("Posted on %A, %d %B %Y")%> by <%= @post.admin.email %>
        </h6>
      </div>
      <div class="shrink column">
        <ul class="menu prev-next-menu remove-first-child-padding">
          <% if @post.previous == nil %>
            <li class="menu-text">
              Prev
            </li>
          <% else %>
            <li>
              <%= link_to "Prev", @post.previous %>
            </li>
          <% end %>

          <li>
            |
          </li>

          <% if @post.next == nil %>
            <li class="menu-text">
              Next
            </li>
          <% else %>
            <li>
              <%= link_to "Next", @post.next %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <hr />

    <%= @post.content.html_safe %>

  </div>
</div>

app/views/shared/_breadcrumbs.html.erb
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li>
      <strong><%= link_to "All Photos", photos_path %></strong>
    </li>
    <li>
      <strong><%= link_to "Albums", albums_path %></strong>
    </li>
    <% if params[:controller] == "albums" && params[:action] == "show" %>
      <li>
        <strong><span class="show-for-sr">Current: </span> <%= @album.name %></strong>
      </li>
    <% else %>
      <li>
        <strong><%= link_to @album.name, @album %></strong>
      </li>
      <li>
        <strong><span class="show-for-sr">Current: </span> Edit</strong>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_gallery.html.erb
<div class="row photo-gallery">
  <% gallery.each do |photo| %>
    <div class="small-6 medium-4 large-3 column photo-container">
      <%= link_to photo.image_url, class: "photo-link", data: {size: "#{photo.image.width}x#{photo.image.height}"} do %>
        <img style="background-image:url(<%= photo.image_url %>);" class="photo-image" />
      <% end %>
      <% if edit %>
        <%= check_box_tag 'photos[]', photo.id, false %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_photoswipe.html.erb
<!-- Root element of PhotoSwipe. Must have class pswp. -->
<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

  <!-- Background of PhotoSwipe.
         It's a separate element, as animating opacity is faster than rgba(). -->
  <div class="pswp__bg"></div>

  <!-- Slides wrapper with overflow:hidden. -->
  <div class="pswp__scroll-wrap">

    <!-- Container that holds slides. PhotoSwipe keeps only 3 slides in DOM to save memory. -->
    <!-- don't modify these 3 pswp__item elements, data is added later on. -->
    <div class="pswp__container">
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
    </div>

    <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
    <div class="pswp__ui pswp__ui--hidden">

      <div class="pswp__top-bar">

        <!--  Controls are self-explanatory. Order can be changed. -->

        <div class="pswp__counter"></div>

        <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>

        <button class="pswp__button pswp__button--share" title="Share"></button>

        <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>

        <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

        <!-- Preloader demo http://codepen.io/dimsemenov/pen/yyBWoR -->
        <!-- element will get class pswp__preloader--active when preloader is running -->
        <div class="pswp__preloader">
          <div class="pswp__preloader__icn">
            <div class="pswp__preloader__cut">
              <div class="pswp__preloader__donut"></div>
            </div>
          </div>
        </div>
      </div>

      <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
        <div class="pswp__share-tooltip"></div>
      </div>

      <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>

      <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>

      <div class="pswp__caption">
        <div class="pswp__caption__center"></div>
      </div>

    </div>

  </div>

</div>

app/views/shared/_tabs.html.erb
<div class="tab-links">
  <div class="row align-middle">
    <div class="column">
      <h4>
        <i class="fa fa-picture-o" aria-hidden="true"></i> Photos
      </h4>
    </div>
    <% if params[:controller] == "albums" %>
      <div class="shrink column">
        <a class="button success add-album-button" data-open="album-form"><i class="fa fa-plus" aria-hidden="true"></i></a>
      </div>
    <% end %>
  </div>

  <ul class="menu remove-first-child-padding">
    <li>
      <%= link_to "All Photos", photos_path, class: params[:controller] == "photos" ? "active" : "" %>
    </li>
    <li>
      <%= link_to "Albums", albums_path, class: params[:controller] == "albums" ? "active" : "" %>
    </li>
  </ul>
</div>